shoot-check plugin doesn't fail on 'the server doesn't have a resource type "shoots"'

diff --git a/plugins/shoot-check/plugin b/plugins/shoot-check/plugin
--- a/plugins/shoot-check/plugin
+++ b/plugins/shoot-check/plugin
@@ -32,20 +32,15 @@ deploy() {
 # if a namespace is given, only look in that namespace for shoots
 # if one or more seeds are given, filter for shoots that use one of these seeds
 delete() {
-    if [ -n ${namespace:-""} ]; then
-        nsmod="-n $namespace"
-    else
-        nsmod="--all-namespaces"
-    fi
     shoots=
     seed=
     if [ ${#seeds[@]} -eq 0 ]; then
         # if no seeds are specified
-        shoots=$(kubectl get shoots $nsmod --no-headers 2> "$dir/error_log.txt") || fail $(cat "$dir/error_log.txt") # don't show "No resources found." message
+        shoots=$(get_shoots ${namespace:-""})
     else
         # if seeds are specified
         for s in ${seeds[@]}; do
-            shoots=$(kubectl get shoots $nsmod --field-selector spec.cloud.seed=$s 2> "$dir/error_log.txt") || fail $(cat "$dir/error_log.txt")
+            shoots=$(get_shoots ${namespace:-""} "$s")
             if [ -n "$shoots" ]; then
                 seed=$s
                 break
@@ -68,6 +63,29 @@ delete() {
     else
         info "No conflicting shoots found."
     fi
+}
+
+get_shoots() {
+    namespace=${1:-""}
+    seed=${2:-""}
+
+    if [ -n "$namespace" ]; then
+        nsmod="-n $namespace"
+    else
+        nsmod="--all-namespaces"
+    fi
+    if [ -n "$seed" ]; then
+        smod="--field-selector spec.cloud.seed=$seed"
+    else
+        smod="--no-headers"
+    fi
+    if ! shoots=$(kubectl get shoots $nsmod $smod 2> "$dir/error_log.txt"); then
+        err=$(cat "$dir/error_log.txt")
+        if [ "$err" != "error: the server doesn't have a resource type \"shoots\"" ]; then
+            fail "$err"
+        fi
+    fi
+    echo "$shoots"
 }
 
 case "$1" in
